# serverless.yml

service: bartbot-serverless

package: 
  exclude:
    # Folders
    - bartbot/__pycache__ 
    - bartbot/**/__pycache__
    - bartbot/.logs
    - bartbot/scripts/*.sh
    - misc/**
    # - node_modules/**
    # - resources/images/**
    - tests
    - tmp/**
    # Files
    - .bartbot-debug.log
    - .bartbot-info.log
    - .git/**
    - .gitignore
    - bartbot.code-workspace
    - contributing.md
    - functionsToImplement.md


plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: bartbot.webhook.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-1

functions:
  app:
    handler: wsgi.handler
    description: Handles Bartbot requests from Facebook Messenger Platform
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      FB_PAGE_ACCESS: ${ssm:fb-page-access}
      FB_PAGE_ACCESS_2: ${ssm:fb-app-access}
      FB_VERIFY_TOKEN: ${ssm:fb-verify-token}
      DARK_SKY_PRIV: ${ssm:dark-sky-priv}
      BART_PUBL: ${ssm:bart-publ}
      BART_PRIV: ${ssm:bart-priv}
      WIT_TOKEN: ${ssm:wit-server-token}
